name = "xray"
main = "build/worker/shim.mjs"
compatibility_date = "2024-05-23"
minify = true


account_id = "69b58c2aee33033db7f2917bceec146a"
workers_dev = true

[[kv_namespaces]]
binding = "YUMI"
id = "8ff1913fa986482d967e0a5c7e2b0791"

[build]
command = "cargo install worker-build && worker-build --release"

[env.dev]
build = { command = "cargo install worker-build && worker-build --dev" }

[vars]
UUID = "2bcfbfba-b446-4ad5-93ad-72af9e008f61"
