name: Deploy Xray Worker

on:
  workflow_dispatch:

  push:
    branches:
      - master
      - main
    paths-ignore:
      - 'README.md'
      - 'LICENSE.md'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: cf

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Install worker-build
        run: cargo install worker-build

      - name: Build Rust Worker
        run: worker-build --release

      - name: Deploy to Cloudflare
        uses: cloudflare/wrangler-action@v3
        with:
              apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
              accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
              wranglerVersion: "4"
              command: deploy
